server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: swiggy-service
          uri: lb://SWIGGY-APP
          predicates:
            - Path=/swiggy/**

        - id: restaurent-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: SWIGGY-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/